// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJkcHWP5eYiRe3sVVPqCxz3zBI-gRB584',
    appId: '1:614548459975:web:469d14d84b1ddb4373c9e2',
    messagingSenderId: '614548459975',
    projectId: 'fir-2-37cce',
    authDomain: 'fir-2-37cce.firebaseapp.com',
    storageBucket: 'fir-2-37cce.appspot.com',
    measurementId: 'G-TCVJG7LRM3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNm5UesPDO70X2HhX-1kbmW-Z4F5s9F_s',
    appId: '1:614548459975:android:1d86e7a9cfc4dfb773c9e2',
    messagingSenderId: '614548459975',
    projectId: 'fir-2-37cce',
    storageBucket: 'fir-2-37cce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByAveSfj3gi_Z_sM-QGvD9XYaBpTSJFus',
    appId: '1:614548459975:ios:35c110bdb5b9300d73c9e2',
    messagingSenderId: '614548459975',
    projectId: 'fir-2-37cce',
    storageBucket: 'fir-2-37cce.appspot.com',
    iosClientId: '614548459975-kctfm3illgvsdtcu4pl13murp12kj5dh.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByAveSfj3gi_Z_sM-QGvD9XYaBpTSJFus',
    appId: '1:614548459975:ios:35c110bdb5b9300d73c9e2',
    messagingSenderId: '614548459975',
    projectId: 'fir-2-37cce',
    storageBucket: 'fir-2-37cce.appspot.com',
    iosClientId: '614548459975-kctfm3illgvsdtcu4pl13murp12kj5dh.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseTest',
  );
}
